W='mx-auto max-w-6xl px-5'
TC=['border-t-violet-500','border-t-pink-500','border-t-orange-400','border-t-cyan-400']
PC=['bg-violet-100 text-violet-700','bg-pink-100 text-pink-700','bg-orange-100 text-orange-700','bg-cyan-100 text-cyan-700','bg-emerald-100 text-emerald-700']
MQ=['🎓 No charge unless funded','👕 Class hoodies','🔒 Escrow-protected','🍿 Snack boxes','✅ Udyam-verified founders','🎟️ Fest passes','📲 UPI AutoPay','📚 Stationery','🛡️ Full refund guarantee','🎒 Tote bags']
MARQ='<div class="overflow-hidden border-y border-line bg-white py-4"><div class="marq">'+''.join('<span class="mx-1.5 whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold %s">%s</span>'%(PC[i%5],t) for i,t in enumerate(MQ*2))+'</div></div>'
WAVE='<div class="§"><svg viewBox="0 0 1200 30" class="h-8 w-full" preserveAspectRatio="none"><defs><linearGradient id="wg"><stop offset="0" stop-color="#6d3cf0"/><stop offset=".5" stop-color="#ec4899"/><stop offset="1" stop-color="#fb923c"/></linearGradient></defs><path class="animate-dash" d="M0 15 Q150 -5 300 15 T600 15 T900 15 T1200 15" fill="none" stroke="url(#wg)" stroke-width="3" stroke-linecap="round"/></svg></div>'
def sc(items):return '<div class="mt-10 grid gap-5 md:grid-cols-3">'+''.join('<div class="reveal rounded-2xl bg-gradient-to-br %s p-6 transition hover:-rotate-1 hover:scale-[1.02]"><div class="text-4xl">%s</div><h3 class="mt-3 font-display text-xl font-bold">%s</h3><p class="mt-1 text-slate-700">%s</p></div>'%(g,e,t,d) for g,(e,t,d) in zip(['from-violet-100 to-pink-100','from-cyan-100 to-sky-100','from-orange-100 to-amber-100'],items))+'</div>'
LK=[('discover.html','Discover'),('how-it-works.html','How it works'),('trust.html','Trust &amp; safety'),('faq.html','FAQ')]
def layout(f,t,d,body,page=''):
    nl=''.join('<a href="%s" class="nl">%s</a>'%l for l in LK)
    ml=''.join('<a href="%s" class="block py-2 font-medium">%s</a>'%l for l in LK)
    fl=lambda h,items:'<div><h4 class="mb-3 font-semibold text-white">%s</h4>%s</div>'%(h,''.join('<a href="%s" class="block py-1 text-white/70 transition hover:text-white">%s</a>'%i for i in items))
    html='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%s | Demandra</title><meta name="description" content="%s"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="icon" href="assets/logo.svg"><link rel="stylesheet" href="assets/style.css"><script src="assets/app.js" defer></script></head><body data-page="%s" class="bg-white font-sans text-ink antialiased">
<header class="sticky top-0 z-40 border-b border-line/70 bg-white/85 backdrop-blur"><div class="§ flex h-16 items-center gap-6"><a href="index.html" class="flex items-center gap-2 font-display text-2xl font-semibold"><svg viewBox="0 0 32 32" class="h-9 w-9" aria-hidden="true"><defs><linearGradient id="lg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#6d3cf0"/><stop offset=".6" stop-color="#ec4899"/><stop offset="1" stop-color="#fb923c"/></linearGradient></defs><path d="M16 2l11 4v9c0 7-4.6 12.2-11 15C9.6 27.2 5 22 5 15V6z" fill="url(#lg)"/><path d="M10.5 16.5l4 4 7-8" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="font-display text-[22px] font-extrabold tracking-tight">Demandra<span class="text-brand">.</span></span></a><nav class="ml-auto hidden items-center gap-1 md:flex">%s<span id="auth" class="ml-3 flex items-center gap-2"></span></nav><button id="mb" aria-label="Menu" class="ml-auto grid h-10 w-10 place-items-center rounded-lg border border-slate-200 md:hidden">☰</button></div><div id="mm" class="hidden border-t border-line bg-white px-5 py-3 md:hidden">%s<div id="auth2" class="mt-2 flex items-center gap-2"></div></div></header>
<main>%s</main>
<footer class="border-t-4 border-fuchsia-500 bg-ink py-14 text-sm text-white/70"><div class="§ grid gap-8 md:grid-cols-4"><div><div class="flex items-center gap-2"><svg viewBox="0 0 32 32" class="h-9 w-9" aria-hidden="true"><path d="M16 2l11 4v9c0 7-4.6 12.2-11 15C9.6 27.2 5 22 5 15V6z" fill="#fff"/><path d="M10.5 16.5l4 4 7-8" fill="none" stroke="#6d3cf0" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="font-display text-2xl font-extrabold text-white">Demandra.</span></div><p class="mt-3 max-w-xs">Pre-order first, produce only when demand is proven. Built for student founders.</p></div>%s%s%s</div><div class="§ mt-10 border-t border-white/10 pt-6 text-xs">© 2026 Demandra, Department of Business Administration, Madras Christian College (Autonomous), East Tambaram, Chennai 600059. Payments are processed by Razorpay; Demandra never holds your money. Campaigns shown are sample listings for the pilot.</div></footer></body></html>'''%(t,d,page,nl,ml,body,
      fl('Platform',[('discover.html','Discover'),('launch.html','Launch a campaign'),('how-it-works.html','How it works')]),
      fl('Trust',[('trust.html','Trust &amp; safety'),('escrow.html','Escrow policy'),('faq.html','FAQ')]),
      fl('Legal',[('privacy.html','Privacy policy'),('refund.html','Refund policy'),('terms.html','Terms of use'),('contact.html','Contact')]))
    open(f,'w').write(html.replace('§',W))
def head(t,s):return '<section class="relative overflow-hidden bg-gradient-to-r from-violet-100 via-pink-100 to-orange-100"><div class="lines absolute inset-0"></div><div class="§ relative py-14 md:py-20"><h1 class="animate-up font-display text-4xl font-semibold tracking-tight md:text-6xl">%s</h1><p class="animate-up mt-3 max-w-2xl text-lg text-slate-600" style="animation-delay:.1s">%s</p></div></section>'%(t,s)
def H(t,s=''):return '<div class="reveal max-w-2xl"><h2 class="font-display text-3xl font-semibold tracking-tight md:text-5xl">%s</h2>%s</div>'%(t,'<p class="mt-3 text-lg text-slate-600">%s</p>'%s if s else '')
G={2:'md:grid-cols-2',3:'md:grid-cols-3',4:'md:grid-cols-2 lg:grid-cols-4'}
def grid(items,n=3):return '<div class="mt-10 grid gap-5 %s">%s</div>'%(G[n],''.join('<div class="reveal card border-t-4 %s"><h3 class="font-display text-xl font-semibold">%s</h3><p class="mt-2 text-slate-600">%s</p></div>'%((TC[k%4],)+i) for k,i in enumerate(items)))
def table(rows,h=('Stage','Where your money is')):return '<div class="reveal card overflow-x-auto !p-2"><table class="w-full text-left text-sm"><tr class="text-slate-500"><th class="p-3">%s</th><th class="p-3">%s</th></tr>%s</table></div>'%(h+(''.join('<tr class="border-t border-slate-100"><td class="p-3 font-semibold">%s</td><td class="p-3 text-slate-600">%s</td></tr>'%r for r in rows),))
def sec(b,alt=False):return '<section class="%s"><div class="§ py-16 md:py-24">%s</div></section>'%('border-y border-line bg-gradient-to-b from-violet-50 via-white to-pink-50' if alt else '',b)
MONEY=[('Campaign running','In your bank. Nothing is debited.'),('Target missed','In your bank. The mandate cancels automatically.'),('Target met (110%)','Collected into a nodal escrow account via Razorpay.'),('Founder verified','Still in escrow. 40% is released against vendor invoices.'),('You collect your product','A QR scan releases the final 60%.'),('Something goes wrong','Escrow funds are used to refund you.')]
COMMIT='<ul class="mt-3 space-y-2 text-slate-600">%s</ul>'%''.join('<li>✓ %s</li>'%x for x in ['We never hold your money ourselves.','We never store card numbers or UPI PINs.','No founder is paid before Udyam registration.','Every vendor is pre-screened and signs a delivery agreement.','We never sell your data.'])
CTA='<section><div class="§ pb-20"><div class="reveal relative overflow-hidden rounded-[28px] bg-gradient-to-br from-brand via-fuchsia-500 to-orange-400 px-6 py-16 text-center text-white"><div class="lines-w absolute inset-0"></div><div class="blob -left-10 -top-10 h-56 w-56 bg-cyan-300"></div><h2 class="relative font-display text-3xl font-semibold md:text-5xl">Test your idea before you build it.</h2><p class="relative mx-auto mb-7 mt-3 max-w-xl text-white/80">List a campaign for free. You pay nothing unless it is funded.</p><a href="launch.html" class="relative inline-flex rounded-xl bg-white px-7 py-3.5 font-semibold text-brand transition hover:-translate-y-0.5">Launch a campaign</a></div></div></section>'
def stat(n,dec,suf,d):return '<div class="reveal border-white/15 md:border-l md:pl-7 first:border-0 first:pl-0"><div class="font-display text-5xl font-extrabold text-amber-300" data-count="%s" data-dec="%s" data-suf="%s">0</div><p class="mt-2 text-sm text-white/70">%s</p></div>'%(n,dec,suf,d)
home='''<section class="relative overflow-hidden"><div class="lines absolute inset-0"></div><div class="blob -right-20 -top-20 h-96 w-96 bg-pink-300"></div><div class="blob left-[-80px] top-60 h-80 w-80 bg-violet-300" style="animation-delay:-5s"></div><div class="blob bottom-0 right-1/3 h-72 w-72 bg-orange-200" style="animation-delay:-9s"></div><div class="§ relative grid items-center gap-14 py-14 md:grid-cols-2 md:py-24"><div><span class="animate-up inline-block rounded-full bg-brand-soft px-3 py-1 text-xs font-semibold text-brand">🎓 Made by students, for students</span><h1 class="animate-up mt-5 font-display text-5xl font-semibold leading-[1.05] tracking-tight md:text-6xl" style="animation-delay:.1s">Know people will buy <span class="grad-text">before you build.</span><svg class="squig mt-1 block w-56" viewBox="0 0 220 12"><path d="M2 8 Q30 0 55 7 T110 7 T165 7 T218 6" fill="none" stroke="#ec4899" stroke-width="4" stroke-linecap="round"/></svg></h1><p class="animate-up mt-5 max-w-lg text-lg text-slate-600" style="animation-delay:.2s">Demandra is a pre-order platform for student founders. Buyers back an idea with nothing to pay upfront. Money is collected only if the target is met, then held in escrow until delivery.</p><div class="animate-up mt-8 flex flex-wrap gap-3" style="animation-delay:.3s"><a class="btn" href="launch.html">Launch a campaign</a><a class="btn-o" href="discover.html">Browse and back ideas</a></div><ul class="animate-up mt-6 flex flex-wrap gap-x-5 gap-y-1 text-sm text-slate-500" style="animation-delay:.4s"><li>✓ No charge unless funded</li><li>✓ Razorpay UPI AutoPay</li><li>✓ Escrow-protected</li></ul></div>
<div class="animate-up relative rounded-[28px] bg-gradient-to-br from-brand via-fuchsia-500 to-orange-400 px-5 py-14 md:px-8" style="animation-delay:.25s"><span class="animate-float absolute -top-4 left-7 rounded-xl bg-white px-4 py-2 text-sm font-semibold shadow-lg">🔒 Held in escrow</span><div id="demo" class="rounded-2xl bg-white p-6 shadow-2xl"><div class="flex justify-between text-sm"><b>MCC Fest Hoodie</b><span class="text-slate-500">Target: 75 orders</span></div><div class="my-4 flex rounded-xl bg-brand-soft p-1"><button id="d1" class="flex-1 rounded-lg py-2 text-sm font-semibold">Target reached</button><button id="d2" class="flex-1 rounded-lg py-2 text-sm font-semibold">Target missed</button></div><div class="h-2.5 overflow-hidden rounded-full bg-slate-100"><i id="db" class="block h-full w-0 rounded-full"></i></div><div class="mt-2 flex justify-between text-sm"><span id="dp"></span><b id="dpc"></b></div><p id="dn" class="mt-4 min-h-[5.5rem] rounded-xl bg-brand-soft p-3 text-sm"></p></div><span class="animate-float absolute -bottom-4 right-7 rounded-xl bg-white px-4 py-2 text-sm font-semibold shadow-lg" style="animation-delay:1.5s">✓ ₹0 charged if target missed</span></div></div></section>
'''+MARQ
home+=sec('<div class="grid items-center gap-12 md:grid-cols-2"><div class="reveal"><h2 class="font-display text-3xl font-semibold tracking-tight md:text-5xl">A friendly “I’d buy that” is not an order.</h2><p class="mt-4 text-slate-600">Most student ventures begin the same way: ask friends, hear “sounds good”, pay for production, and end up with unsold stock.</p><p class="mt-3 text-slate-600">Demandra replaces guesswork with conditional pre-orders. A founder sets a minimum target and buyers back the idea. If enough people commit, the product is made. If not, nobody loses a rupee, and the founder learns what to change before spending anything.</p></div><div class="grid gap-4 sm:grid-cols-2"><div class="reveal card"><h3 class="font-display text-xl font-semibold">Without Demandra</h3><ul class="mt-3 space-y-2 text-slate-600"><li><span class="text-red-500">✕</span> Opinions, not orders</li><li><span class="text-red-500">✕</span> Pay for stock upfront</li><li><span class="text-red-500">✕</span> Unsold inventory</li></ul></div><div class="reveal card border-brand/30 bg-brand-soft"><h3 class="font-display text-xl font-semibold">With Demandra</h3><ul class="mt-3 space-y-2"><li><span class="text-emerald-600">✓</span> Real demand data</li><li><span class="text-emerald-600">✓</span> Zero upfront risk</li><li><span class="text-emerald-600">✓</span> Build only after proof</li></ul></div></div></div>')
home+='<div class="relative overflow-hidden bg-gradient-to-r from-[#1b1340] via-[#4c1d95] to-[#a21caf] py-14 text-white"><div class="lines-w absolute inset-0"></div><div class="§ relative grid gap-8 md:grid-cols-4">'+stat('4.3',1,' crore+','students across 55,000+ institutions in India')+stat('0',0,'','rupees charged if a campaign misses its target')+stat('110',0,'%','funding buffer, so a funded campaign stays funded')+stat('60',0,'%','of funds held in escrow until delivery is verified')+'</div></div>'
home+=sec(H('Made for how students actually buy','Group chats, fests and class merch: Demandra fits the way campus ideas already spread.')+sc([('📱','Share it in your class group','Every campaign has a WhatsApp share link. Friends pre-commit in seconds.'),('🎽','Fests, clubs and class merch','Hoodies, fest passes, snacks, stationery. Test what people want before paying for stock.'),('⚡','Back in under a minute','Pick an option and approve UPI AutoPay once. No card needed.')]))
home+=sec(H('How it works','From idea to delivered product, with the buyer protected at every step.')+grid([('1. Founder lists','A product, an early-bird price and a minimum order target.'),('2. Buyers back it','Validate, say you will buy, or pre-commit with UPI AutoPay. Nothing is debited.'),('3. Target is checked','At 110%, payments go to escrow. If missed, mandates cancel and nobody pays.'),('4. Verified delivery','Udyam check, 40% on invoices, 60% after a QR-confirmed pickup.')],4)+'<a href="how-it-works.html" class="mt-6 inline-block font-semibold text-brand">See the full process →</a>',True)
home+=WAVE
home+=sec(H('Three ways to back an idea','Show as much or as little commitment as you like. Founders see every signal.')+'<div class="mt-10 grid gap-5 md:grid-cols-3"><div class="reveal card !border-0 bg-gradient-to-br from-cyan-100 to-sky-50"><h3 class="font-display text-xl font-semibold">Validate demand</h3><p class="mt-2 text-slate-600">You like the idea and want it made. No commitment, no payment.</p></div><div class="reveal card !border-0 bg-gradient-to-br from-orange-100 to-amber-50"><h3 class="font-display text-xl font-semibold">Will buy if it comes</h3><p class="mt-2 text-slate-600">You intend to buy once it launches. No payment now.</p></div><div class="reveal card !border-0 bg-gradient-to-br from-brand via-fuchsia-500 to-orange-400 text-white"><span class="rounded-full bg-white px-2.5 py-0.5 text-xs font-semibold text-brand">Counts toward the target</span><h3 class="mt-3 font-display text-xl font-semibold">Pre-commit</h3><p class="mt-2 text-white/80">Approve a UPI AutoPay mandate. ₹0 today, charged only if the campaign is funded.</p></div></div>')
TF=[('Escrow-held funds','Collected into a nodal escrow account. Demandra never touches your money.'),('Udyam-verified founders','No payout until a valid MSME certificate is submitted.'),('Contract-bound vendors','Every vendor signs an SLA covering delivery date, quality and sample approval.'),('QR-confirmed delivery','The final 60% is released only after you scan at pickup.'),('Full refund guarantee','Not delivered or not as described? You get your money back.'),('Privacy by design','We never store card or UPI PIN details, and never sell your data.')]
ICON='<span class="mb-3 grid h-10 w-10 place-items-center rounded-full bg-brand-soft font-bold text-brand">✓</span>'
VER='<div class="reveal card border-brand/30"><span class="rounded-full bg-brand px-3 py-1 text-xs font-semibold text-white">Verified by Demandra</span><h3 class="mt-4 font-display text-xl font-bold">Five checks before any campaign goes live</h3><ul class="mt-4 divide-y divide-slate-100">'+''.join('<li class="flex items-center gap-3 py-2.5"><span class="grid h-6 w-6 place-items-center rounded-full bg-brand text-xs text-white">✓</span>%s</li>'%x for x in ['College ID verified','Udyam registration submitted','Vendor SLA signed','Product sample approved','Delivery date committed'])+'</ul></div>'
home+=sec('<div class="grid items-center gap-12 md:grid-cols-2"><div>'+H('Trust, verified at every step','Six safeguards stand between your money and a bad outcome.')+'<div class="mt-8 grid gap-4 sm:grid-cols-2">'+''.join('<div class="reveal">'+ICON+'<h3 class="font-display font-bold">%s</h3><p class="mt-1 text-sm text-slate-600">%s</p></div>'%t for t in TF)+'</div></div>'+VER+'</div>')
home+=sec(H('Why you can trust Demandra','Trust is the whole product, so we built it into how money moves.')+'<div class="mt-10 grid gap-6 md:grid-cols-5"><div class="md:col-span-3">'+table(MONEY)+'</div><div class="reveal card md:col-span-2"><h3 class="font-display text-xl font-semibold">Our commitments</h3>'+COMMIT+'<p class="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-600">Built by Rukayya Afra KS and V Manish Kumar, Business Administration students at Madras Christian College. <a class="text-brand underline" href="contact.html">Contact us</a>.</p></div></div>',True)
home+=sec('<div class="flex items-end justify-between gap-4">'+H('Live campaigns')+'<a href="discover.html" class="font-semibold text-brand">See all →</a></div><div id="home-feed" class="mt-10 grid gap-5 md:grid-cols-3"></div>')
home+=sec(H('Built for everyone around a campus idea')+grid([('Student founders','Free listing, real demand data, MSME help and a verified first-customer list.'),('Departments and IICs','Test student projects on Demandra before sanctioning budgets.'),('Incubators','Receive registered ventures that already have paying customers.'),('Brands','Test FMCG and D2C concepts with real college buyers.')],4),True)+CTA
layout('index.html','Demand before supply','Demandra: conditional pre-orders for student founders. No charge unless funded, escrow-protected.',home,'home')
layout('discover.html','Discover campaigns','Back campus ideas with no upfront charge.',head('Discover campaigns','Back an idea with no upfront payment. You pay only if it reaches its target.')+sec('<input id="q" type="search" placeholder="Search campaigns" class="inp mb-4 max-w-md"><div id="chips" class="mb-8 flex flex-wrap gap-2"></div><div id="feed" class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"></div>'),'discover')
layout('campaign.html','Campaign','Campaign details','<section><div id="detail" class="§ grid gap-10 py-10 md:grid-cols-[1.5fr_1fr] md:py-14"></div></section>','campaign')
steps=[('Create','A founder lists a product, an early-bird price and a minimum order target.'),('Commit','Buyers choose to validate demand, say they will buy, or pre-commit with a UPI AutoPay mandate. Nothing is deducted during the campaign.'),('Validate','If pre-commits reach 110% of the minimum, payments are collected into escrow. The buffer covers failed debits. If the target is missed, mandates expire and nobody pays.'),('Register and release','The founder submits a Udyam MSME certificate. 40% is released against vendor invoices and 60% after QR-verified campus delivery.'),('Incubate','Proven, registered ventures are referred to incubators, EDII-TN cells and seed grant committees.'),('Brand sandbox','FMCG and D2C brands test product concepts with real college buyers.')]
tl='<div class="relative space-y-8 border-l-2 border-line pl-10">'+''.join('<div class="reveal relative"><span class="absolute -left-[3.4rem] grid h-10 w-10 place-items-center rounded-full bg-brand font-bold text-white">%d</span><h3 class="font-display text-2xl font-semibold">%s</h3><p class="mt-1 text-slate-600">%s</p></div>'%(i+1,a,b) for i,(a,b) in enumerate(steps))+'</div>'
layout('how-it-works.html','How it works','Six steps from idea to delivered product.',head('How Demandra works','Six steps from idea to delivered product, with your money protected at every one.')+sec(tl)+sec(H('Simple, transparent fees')+'<div class="mt-8">'+table([('Listing a campaign','Free'),('Platform commission','5%, only on funded campaigns'),('Payment gateway fee','About 2%, paid by the creator'),('Udyam registration','Free if self-filed, ₹499 if assisted'),('Backers','No fee')],('Item','Cost'))+'</div>',True)+CTA)
layout('trust.html','Trust & safety','How Demandra protects your money.',head('Trust and safety','Trust is the whole product. This is how we protect you.')+sec(grid([('We never hold your money','Payments run on Razorpay’s RBI-compliant rails into a nodal escrow account.'),('Staged payouts','Founders get 40% against invoices and 60% only after verified delivery.'),('Verified ventures','No payout without a valid Udyam MSME certificate.'),('Pre-screened vendors','Each vendor signs an agreement covering delivery date, quality and sample approval.'),('Clear refunds','Undelivered or mismatched products are refunded in full.'),('Your data stays yours','We never store card or UPI PIN details and never sell personal data.')])+'<div class="mt-12">'+H('Where your money is, at every stage')+'<div class="mt-6">'+table(MONEY)+'</div></div><p class="mt-8 text-slate-600"><a class="text-brand underline" href="escrow.html">Escrow policy</a> · <a class="text-brand underline" href="refund.html">Refund policy</a> · <a class="text-brand underline" href="privacy.html">Privacy policy</a></p>')+CTA)
faq=[('Will I be charged when I back an idea?','No. Validate demand and Will buy cost nothing. Pre-commit only approves a UPI AutoPay mandate, and you are debited only if the campaign is funded.'),('What is the difference between the three options?','Validate demand and Will buy are free signals that show the founder how much interest exists. Pre-commit is a conditional order and the only one that counts toward the funding target.'),('What if the founder disappears with the money?','They cannot. Funds sit in escrow. Only 40% is released against vendor invoices, and 60% is held until you receive the product.'),('Why 110% and not 100%?','Some debits fail because of bank downtime or low balance. The buffer keeps a funded campaign funded.'),('How do I get my product?','Collect it on campus and scan a QR code. That confirms delivery and releases the final payment.'),('Can I cancel a pre-commit?','Yes, any time before the campaign ends. After funding, refunds follow our refund policy.'),('Is it free for founders?','Listing is free. We keep 5% of funded campaigns only.'),('What do brands and incubators get?','Brands test concepts with real college buyers. Incubators receive registered ventures that already have paying customers.'),('Who is behind Demandra?','Rukayya Afra KS and V Manish Kumar, Business Administration students at Madras Christian College.')]
layout('faq.html','FAQ','Answers to common questions.',head('Frequently asked questions','Quick answers about pre-commits, escrow and refunds.')+sec('<div class="max-w-3xl space-y-3">'+''.join('<details class="reveal card group !p-5"><summary class="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold">%s<span class="text-2xl text-brand transition group-open:rotate-45">+</span></summary><p class="mt-3 text-slate-600">%s</p></details>'%q for q in faq)+'</div>'),'faq')
layout('login.html','Log in','Log in or create your Demandra account.','<section class="bg-brand-soft"><div class="mx-auto max-w-md px-5 py-14 md:py-20"><h1 class="animate-up text-center font-display text-4xl font-semibold">Welcome to Demandra</h1><p class="mb-6 mt-2 text-center text-slate-600">Back ideas or launch your own. It is free.</p><form id="af" class="card animate-up" style="animation-delay:.1s"></form><p class="mt-4 text-center text-xs text-slate-500">🔒 We never see your card or UPI PIN. By continuing you agree to our <a class="underline" href="terms.html">Terms</a> and <a class="underline" href="privacy.html">Privacy policy</a>.</p></div></section>','login')
fld=lambda l,i,t='text':'<label class="mb-1 mt-4 block text-sm font-semibold">%s</label><input required id="%s" type="%s" class="inp">'%(l,i,t)
layout('launch.html','Launch a campaign','List your product and test demand for free.','<section class="bg-brand-soft"><div class="mx-auto max-w-xl px-5 py-14 md:py-20"><h1 class="animate-up font-display text-4xl font-semibold">Launch a campaign</h1><p class="mb-6 mt-2 text-slate-600">Listing is free. We earn 5% only if you are funded.</p><form id="lf" class="card">'+fld('Product name','a')+fld('Early-bird price (₹)','b','number')+fld('Minimum order target','c','number')+'<label class="mb-1 mt-4 block text-sm font-semibold">Short description</label><textarea required rows="3" class="inp"></textarea><button class="btn mt-5 w-full">Submit for review</button><p class="mt-3 text-xs text-slate-500">Your campaign goes live after we verify you and your vendor.</p></form></div></section>','launch')
layout('contact.html','Contact','Contact the Demandra team.',head('Contact us','We reply within two working days.')+sec('<div class="grid gap-5 md:grid-cols-2"><div class="reveal card"><h3 class="font-display text-xl font-semibold">Rukayya Afra KS</h3><p class="mt-2 text-slate-600">rukayya.afra@gmail.com<br>+91 90800 37159</p></div><div class="reveal card"><h3 class="font-display text-xl font-semibold">V Manish Kumar</h3><p class="mt-2 text-slate-600">manishkumariam@gmail.com<br>+91 93456 63013</p></div></div><form id="cf" class="reveal card mt-6 max-w-xl">'+fld('Your name','cn')+fld('Subject','cs')+'<label class="mb-1 mt-4 block text-sm font-semibold">Message</label><textarea required id="cm" rows="4" class="inp"></textarea><button class="btn mt-5 w-full">Send message</button></form><p class="mt-6 text-slate-600">Department of Business Administration, Madras Christian College (Autonomous), East Tambaram, Chennai – 600059, Tamil Nadu.</p>'),'contact')
def legal(f,t,b):layout(f,t,t,head(t,'Last updated 1 October 2026')+'<section><div class="§ py-14"><div class="doc max-w-3xl">%s</div></div></section>'%b)
legal('privacy.html','Privacy policy','<p>Demandra is run by students of the Department of Business Administration, Madras Christian College. This policy explains what we collect and why, in line with India’s Digital Personal Data Protection Act, 2023.</p><h2>What we collect</h2><ul><li>Account details: name, email, phone number, college.</li><li>Order details: campaigns backed and your pickup location on campus.</li><li>Founder details: Udyam registration number, vendor invoices and delivery proof.</li><li>Basic usage data such as device type and pages visited.</li></ul><h2>What we never collect</h2><p>We never see or store your card number, UPI PIN or bank login. These stay with Razorpay and your bank.</p><h2>How we use it</h2><ul><li>To run campaigns, confirm orders and verify delivery.</li><li>To share your name and pickup details with the founder of a campaign you pre-committed to, only after it is funded.</li><li>To share a founder’s verified details with incubators, only with that founder’s consent.</li><li>To prevent fraud and meet legal duties.</li></ul><h2>Sharing</h2><p>We share data only with Razorpay, our hosting providers, and authorities when the law requires. We never sell personal data.</p><h2>Your rights</h2><p>You can ask to access, correct or delete your data, or withdraw consent, by emailing us. We reply within 15 days. Records we must keep by law are retained for the period required.</p><h2>Grievance contact</h2><p>rukayya.afra@gmail.com</p>')
legal('refund.html','Refund policy','<p>Demandra is built so most refunds are never needed: you are not charged unless a campaign succeeds.</p><h2>If a campaign misses its target</h2><p>Your UPI AutoPay mandate expires automatically. Nothing is debited, so there is nothing to refund.</p><h2>If a campaign is funded</h2><ul><li>You are charged once, on the campaign end date.</li><li>The money goes to a nodal escrow account, not to the founder.</li><li>The founder is paid 40% against vendor invoices and 60% only after delivery is verified by QR scan.</li></ul><h2>You get a full refund if</h2><ul><li>The founder does not complete MSME (Udyam) registration.</li><li>The product is not delivered by the promised date, or delivery cannot be verified.</li><li>The product differs materially from the approved sample or listing.</li><li>You were charged twice or by mistake.</li></ul><h2>How to claim</h2><p>Raise a dispute from your account within 7 days of the promised delivery date. We review within 5 working days. Approved refunds return to the original UPI account within 5 to 7 working days.</p><h2>Not covered</h2><p>Change of mind after successful delivery, or damage after you collect the product.</p>')
legal('terms.html','Terms of use','<h2>1. Who can use Demandra</h2><p>Students and staff of partner colleges, aged 18 or above, with a valid college email or ID.</p><h2>2. Founders</h2><ul><li>List only products you can deliver.</li><li>Use only pre-screened campus vendors who sign our delivery agreement.</li><li>Submit a valid Udyam certificate before funds are released.</li><li>Do not list illegal, unsafe or counterfeit goods.</li></ul><h2>3. Backers</h2><p>You can validate demand, say you will buy, or pre-commit. Only a pre-commit is a conditional order: by pre-committing you authorise Razorpay to debit you only if the campaign is funded at its end date.</p><h2>4. Fees</h2><p>Listing is free. Demandra keeps 5% of a funded campaign. The payment gateway fee (about 2%) is paid by the founder. Optional MSME filing help costs ₹499.</p><h2>5. Funding threshold</h2><p>To allow for failed debits, a campaign is funded only when pre-commits reach 110% of the founder’s minimum.</p><h2>6. Liability</h2><p>Demandra verifies founders and vendors but is a facilitator, not the seller. Our liability is limited to the amount of the order in dispute.</p><h2>7. Governing law</h2><p>These terms follow Indian law. Disputes go to the courts at Chennai, Tamil Nadu.</p>')
legal('escrow.html','Escrow and fund release policy','<p>Demandra never holds your money. Collections go through Razorpay’s RBI-regulated payment rails into a nodal escrow account.</p>'+table(MONEY+[('Pledge stage','You approve a UPI AutoPay mandate. No debit.')])+'<p class="mt-6">If delivery fails, the 60% held in escrow is used to refund backers.</p>')
